def print_connection_details(postgres_details):
    print("\nConnection Details:")
    print(f"PostgreSQL Server: {postgres_details['host']}")
    print(f"Database: {postgres_details['db']}")
    print(f"User: {postgres_details['user']}")
    print(f"Password: {postgres_details['password']}")
    print(f"Port: 5432 (Internal to Docker), 5439 (External)")
    print(f"pgAdmin: Accessible at http://localhost:5059")
    print(f"pgAdmin Default Email: admin@example.com")
    print(f"pgAdmin Default Password: admin")
    print("\nTo connect to PostgreSQL using Python:")
    print("import psycopg2")
    print(f"conn = psycopg2.connect(dbname='{postgres_details['db']}', user='{postgres_details['user']}', host='{postgres_details['host']}', password='{postgres_details['password']}', port='5432')")
    print("cur = conn.cursor()")
    print("# Execute queries using cur.execute()")
    print("cur.close()")
    print("conn.close()")
