from .rust_function_extractor import extract_function_and_references as _extract_function_and_references

extract_function_and_references = _extract_function_and_references

__all__ = ['extract_function_and_references']
